version: '3.8'

services:
  app:
    image: evershop/evershop:latest
    container_name: evershop-app
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: 172.31.9.92
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

